version: '3.9'
services:
  mongo-ecomm:
    image: mongo:6.0
    restart: always
    container_name: mongo-ecomm
    volumes:
      - db-mongo-ecomm:/data/db
      - type: bind
        source: ./mongo
        target: /mongo-scripts
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017:27017
    networks:
      - ecomm-network
  ecomm-app:
    image: weversoncelio/ecomm:1.1
    container_name: ecomm-app
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MONGO_SERVER=mongo-ecomm
    networks:
      - ecomm-network
    depends_on:
    - mongo-ecomm

networks:
  ecomm-network:
    driver: bridge
volumes:
  db-mongo-ecomm:
    external: true